// client_Vue/src/views/Login.vue
<template>
  <div class="auth">
    <form class="card auth-card" v-on:submit.prevent="submitHandler()">
      <div class="card-content">
        <span class="auth-title">Words learning</span>
        <div class="input-field">
          <input id="username" type="text" v-model="username" />
          <label for="username">Username</label>
          <small
            class="helper-text invalid"
            v-for="(error, index) of v$.username.$errors"
            :key="index"
          >
            {{ printError(error.$validator, error.$params) }}</small
          >
        </div>
        <div class="input-field">
          <input id="password" type="password" v-model="user_password" />
          <label for="password">Password</label>
          <small
            class="helper-text invalid"
            v-for="(error, index) of v$.user_password.$errors"
            :key="index"
          >
            {{ printError(error.$validator, error.$params) }}</small
          >
        </div>
        <div>
          <button
            class="btn waves-effect waves-light auth-submit"
            type="submit"
          >
            Login
            <i class="material-icons right">send</i>
          </button>
        </div>

        <p class="center">
          Do you have no an account?
          <router-link to="/registration">Register now</router-link>
        </p>
      </div>
    </form>
  </div>
</template>

<script>
import { mapGetters, mapActions } from "vuex";
import messages from "@/utils/messages";
import useVuelidate from "@vuelidate/core";
import { minLength, required } from "@vuelidate/validators";

export default {
  name: "Login",
  setup() {
    return { v$: useVuelidate() };
  },
  data() {
    return {
      username: "",
      user_password: "",
    };
  },
  validations() {
    return {
      username: { required },
      user_password: { required, minLength: minLength(6) },
    };
  },
  computed: {
    ...mapGetters(["ERROR"]),
  },
  mounted() {
    if (messages[this.$route.query.message]) {
      this.$message(messages[this.$route.query.message]);
    }
  },
  methods: {
    ...mapActions(["AUTHORIZATION"]),
    async submitHandler() {
      this.v$.$touch();
      if (this.v$.$error) {
        return;
      }

      const formData = {
        username: this.username,
        user_password: this.user_password,
      };
      try {
        await this.AUTHORIZATION(formData);

        if (this.ERROR) {
          this.$error(this.ERROR);
        } else {
          this.$message("Success login");
          await this.$router.push({ name: "Home" });
        }
      } catch (e) {
        console.log(e);
      }
    },

    printError($name, $param) {
      if ($name === "required") {
        return "Field cannot be empty";
      } else if ($name === "minLength") {
        return "Minimal long must be " + $param.min + " symbol";
      }
    },
  },
};
</script>

<style scoped></style>

// client_Angular/src/app/auth/login/login.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import { FormControl, FormGroup, Validators } from "@angular/forms";
import { Router } from "@angular/router";
import { Subscription } from "rxjs";

import { LoginService } from "./login.service";

@Component({
  selector: "app-auth",
  templateUrl: "./login.component.html",
  styleUrls: ["./login.component.scss"],
})
export class LoginComponent implements OnInit, OnDestroy {
  form: FormGroup | any;
  lSub: Subscription | any;
  constructor(private loginService: LoginService, private router: Router) {}

  ngOnInit(): void {
    this.form = new FormGroup({
      username: new FormControl(null, [
        Validators.required,
        Validators.minLength(3),
      ]),
      password: new FormControl(null, [
        Validators.required,
        Validators.minLength(6),
      ]),
    });
  }

  ngOnDestroy() {
    if (this.lSub) {
      this.lSub.unsubscribe();
    }
  }

  login() {
    this.lSub = this.loginService
      .login({
        username: this.form.value.username,
        user_password: this.form.value.password,
      })
      .subscribe({
        next: () => {
          this.router.navigate(["/home"]);
        },
        error: (error) => {
          console.warn(error);
        },
      });
  }
}

<section class="auth">
  <div class="auth-card">
    <h1 class="auth__title">Words learning login</h1>
    <form
      [formGroup]="form"
      (ngSubmit)="login()"
    >
      <div class="input-field">
        <input
          id="username"
          type="text"
          formControlName="username"
          placeholder="Username"
          [ngClass]="{
            'uncorrect': form.get('username').invalid && form.get('username').touched,
            'correct': form.get('username').valid
           }"
        />
        <span
          class="helper-text invalid"
          *ngIf="form.get('username').invalid && form.get('username').touched"
        >
          <span *ngIf="form.get('username').errors['required']">Cannot be empty</span>
          <span
            *ngIf="form.get('username').errors['minlength'] &&
            form.get('username').errors['minlength']['requiredLength']"
          >
            Cannot be less {{form.get('username').errors['minlength']['requiredLength']}} symbol.
            Now: {{form.get('username').errors['minlength']['actualLength']}}
          </span>
        </span>
      </div>
      <div class="input-field">
        <input
          id="password"
          type="password"
          formControlName="password"
          placeholder="Password"
          [ngClass]="{
            'uncorrect': form.get('password').invalid && form.get('password').touched,
            'correct': form.get('password').valid
           }"
        />
        <span
          class="helper-text invalid"
          *ngIf="form.get('password').invalid && form.get('password').touched"
        >
          <span *ngIf="form.get('password').errors['required']">Cannot be empty</span>
          <span
            *ngIf="form.get('password').errors['minlength'] &&
            form.get('password').errors['minlength']['requiredLength']"
          >
            Cannot be less {{form.get('password').errors['minlength']['requiredLength']}} symbol.
            Now: {{form.get('password').errors['minlength']['actualLength']}}
          </span>
        </span>
      </div>
      <div class="btn">
        <button type="submit" [disabled]="form.invalid">
          Login
        </button>
      </div>
    </form>
    <div class="auth__have">
      <span>
        Do you have no an account?
      </span>
      <a routerLink="/registration">Registration</a>
    </div>
  </div>
</section>
