// client_Angular/src/app/shared/components/header/header.component.ts
import { Component, OnInit } from "@angular/core";
import { Router } from "@angular/router";

import { AuthService } from "src/app/service/auth.service";

@Component({
  selector: "app-header",
  templateUrl: "./header.component.html",
  styleUrls: ["./header.component.scss"],
})
export class HeaderComponent implements OnInit {
  username: string | null = localStorage.getItem("username");

  constructor(private authService: AuthService, private router: Router) {}

  ngOnInit(): void {}

  logout(): void {
    this.authService.logout();
    this.router.navigate(["/login"]);
  }
}

<header class="header">
  <div class="header-container">
    <div class="header-logo">LL</div>
    <div class="header-nav">
      <a class="header-nav__link link" routerLink="/home" routerLinkActive="link_active"> Home </a>
      <a class="header-nav__link link" routerLink="/practice" routerLinkActive="link_active">
        Practice
      </a>
      <a class="header-nav__link link" routerLink="/all_words" routerLinkActive="link_active">
        All my study words
      </a>
      <a class="header-nav__link link" routerLink="/expansion" routerLinkActive="link_active">
        Add new word
      </a>
    </div>
    <div class="header-auth">
      <div class="header-auth__account">
        Your account <a href="">{{ username }}</a>
      </div>
      <div class="header-auth__logout" (click)="logout()">
        <span>Logout</span>
      </div>
    </div>
  </div>
</header>

// client_Vue/src/components/App/Header.vue
<template>
  <header class="header">
    <div class="header-container">
      <div class="header-logo">LL</div>
      <div class="header-nav">
        <router-link class="header-nav__link link" to="/"> Home </router-link>
        <router-link class="header-nav__link link" to="/practice">
          Practice
        </router-link>
        <router-link class="header-nav__link link" to="/all_words">
          All my study words
        </router-link>
        <router-link class="header-nav__link link" to="/expansion">
          Add new word
        </router-link>
      </div>
      <div class="header-auth">
        <div class="header-auth__account">
          Your account <a href="">{{ username }}</a>
        </div>
        <div class="header-auth__logout">
          <span v-on:click.prevent="logout">Logout</span>
        </div>
      </div>
    </div>
  </header>
</template>

<script>
export default {
  name: "Header",
  data() {
    return {
      username: localStorage.username,
    };
  },
  methods: {
    async logout() {
      await this.LOGOUT;
      this.$router.push({
        name: "Login",
        query: { message: "logout" },
      });
    },
  },
};
</script>

<style scoped></style>
