// client/src/views/Registration.vue
<template>
  <div class="auth">
    <form
      class="card auth-card col s12 m2"
      v-on:submit.prevent="submitHandler()"
    >
      <div class="card-content">
        <span class="auth-title">Registration</span>
        <div class="input-field">
          <input
            id="username"
            type="text"
            v-model.trim="username"
            :class="{ invalid: v$.username.$error }"
          />
          <label for="username">Username</label>
          <small
            class="helper-text invalid"
            v-for="(error, index) of v$.username.$errors"
            :key="index"
          >
            {{ printError(error.$validator, error.$params) }}
          </small>
        </div>
        <div class="input-field">
          <input
            id="email"
            type="email"
            v-model.trim="user_email"
            :class="{ invalid: v$.user_email.$error }"
          />
          <label for="email">Email</label>
          <small
            class="helper-text invalid"
            v-for="(error, index) of v$.user_email.$errors"
            :key="index"
          >
            {{ printError(error.$validator, error.$params) }}
          </small>
        </div>
        <div class="input-field">
          <input
            id="password"
            type="password"
            v-model.trim="user_password"
            :class="{ invalid: v$.user_password.$error }"
          />
          <label for="password">Password</label>
          <small
            class="helper-text invalid"
            v-for="(error, index) of v$.user_password.$errors"
            :key="index"
          >
            {{ printError(error.$validator, error.$params) }}
          </small>
        </div>
        <div class="input-field">
          <input
            id="passwordConfirmation"
            type="password"
            v-model.trim="passwordConfirmation"
            :class="{ invalid: v$.passwordConfirmation.$error }"
          />
          <label for="passwordConfirmation">Confirm password</label>
          <small
            class="helper-text invalid"
            v-for="(error, index) of v$.passwordConfirmation.$errors"
            :key="index"
          >
            {{ printError(error.$validator, error.$params) }}
          </small>
        </div>
        <div>
          <p>
            <label>
              <input
                type="checkbox"
                v-on:click="agree = !agree"
                v-model="agree"
              />
              <span>Agreement with the rules</span>
            </label>
          </p>
        </div>
        <div class="d-grid gap-2">
          <div>
            <button
              class="btn waves-effect waves-light auth-submit"
              type="submit"
            >
              Registration
              <i class="material-icons right">send</i>
            </button>
          </div>
        </div>
        <p class="text-center" style="color: #0f0f0f; margin-top: 5px">
          Do you have an account?
          <router-link to="/authorization">Login now!</router-link>
        </p>
      </div>
    </form>
  </div>
</template>

<script>
import { mapGetters, mapActions } from "vuex";
import useVuelidate from "@vuelidate/core";
import { required, email, minLength } from "@vuelidate/validators";

export default {
  name: "Registration",
  setup() {
    return { v$: useVuelidate() };
  },
  data() {
    return {
      user_email: "",
      user_password: "",
      passwordConfirmation: "",
      username: "",
      agree: false,
    };
  },
  validations() {
    return {
      user_email: { required, email },
      user_password: { required, minLength: minLength(6) },
      passwordConfirmation: { required, minLength: minLength(6) },
      username: { required, minLength: minLength(1) },
      agree: { checked: (v) => v },
    };
  },
  computed: {
    ...mapGetters(["ERROR"]),
  },
  methods: {
    ...mapActions(["REGISTRATION"]),
    async submitHandler() {
      this.v$.$touch();
      if (this.v$.$error) {
        return;
      } else if (this.user_password !== this.passwordConfirmation) {
        this.$error("Passwords must coincidence");
        return;
      }
      const formData = {
        username: this.username,
        user_password: this.user_password,
        user_email: this.user_email,
      };
      try {
        await this.REGISTRATION(formData);

        if (this.ERROR) {
          this.$error(this.ERROR);
        } else {
          this.$message("Success authorization");
        }
      } catch (e) {
        console.log(e);
      }
      // this.$router.push({ name: "Home" });
    },

    printError($name, $param) {
      if ($name === "required") {
        return "Field cannot be empty";
      } else if ($name === "user_email") {
        return "Input correct email";
      } else if ($name === "minLength") {
        return "Minimal long must be " + $param.min + " symbol";
      }
    },
  },
};
</script>

<style scoped>
button {
  margin-top: 15px;
  margin-bottom: 25px;
}
</style>

// client_Angular/src/app/auth/registration/registration.component.ts
import { Component, OnDestroy, OnInit } from "@angular/core";
import { FormControl, FormGroup, Validators } from "@angular/forms";
import { Subscription } from "rxjs";

import { RegistrationService } from "./registration.service";
import { Router } from "@angular/router";

@Component({
  selector: "app-registration",
  templateUrl: "./registration.component.html",
  styleUrls: ["./registration.component.scss"],
})
export class RegistrationComponent implements OnInit, OnDestroy {
  form: FormGroup | any;
  rSub: Subscription | any;
  constructor(
    private registrationService: RegistrationService,
    private router: Router
  ) {}

  ngOnInit(): void {
    this.form = new FormGroup({
      username: new FormControl(null, [
        Validators.required,
        Validators.minLength(3),
      ]),
      email: new FormControl(null, [Validators.required, Validators.email]),
      password: new FormControl(null, [
        Validators.required,
        Validators.minLength(6),
      ]),
      passwordConfirmation: new FormControl(null, [
        Validators.required,
        Validators.minLength(6),
      ]),
    });
  }

  ngOnDestroy() {
    if (this.rSub) {
      this.rSub.unsubscribe();
    }
  }

  registration() {
    this.rSub = this.registrationService
      .registration({
        username: this.form.value.username,
        user_email: this.form.value.email,
        user_password: this.form.value.password,
      })
      .subscribe({
        next: () => {
          this.router.navigate(["/login"]);
        },
        error: (error) => {
          console.warn(error);
        },
      });
  }
}

<section class="auth">
  <div class="auth-card">
    <h1 class="auth__title">Words learning registration</h1>
    <form
      [formGroup]="form"
      (ngSubmit)="registration()"
    >
      <div class="input-field">
        <input
          id="username"
          type="text"
          formControlName="username"
          placeholder="Username"
          [ngClass]="{
            'uncorrect': form.get('username').invalid && form.get('username').touched,
            'correct': form.get('username').valid
           }"
        />
        <span
          class="helper-text invalid"
          *ngIf="form.get('username').invalid && form.get('username').touched"
        >
          <span *ngIf="form.get('username').errors['required']">Cannot be empty</span>
          <span
            *ngIf="form.get('username').errors['minlength'] &&
            form.get('username').errors['minlength']['requiredLength']"
          >
            Cannot be less {{form.get('username').errors['minlength']['requiredLength']}} symbol.
            Now: {{form.get('username').errors['minlength']['actualLength']}}
          </span>
        </span>
      </div>
      <div class="input-field">
        <input
          id="email"
          type="email"
          formControlName="email"
          placeholder="Email"
          [ngClass]="{
            'uncorrect': form.get('email').invalid && form.get('email').touched,
            'correct': form.get('email').valid
           }"
        />
        <span
          class="helper-text invalid"
          *ngIf="form.get('email').invalid && form.get('email').touched"
        >
          <span *ngIf="form.get('email').errors['required']">Cannot be empty</span>
          <span
            *ngIf="form.get('username').errors['email']">Uncorrect email</span>
        </span>
      </div>
      <div class="input-field">
        <input
          id="password"
          type="password"
          formControlName="password"
          placeholder="Password"
          [ngClass]="{
            'uncorrect': form.get('password').invalid && form.get('password').touched,
            'correct': form.get('password').valid
           }"
          #password
          [value]="password"
        />
        <span
          class="helper-text invalid"
          *ngIf="form.get('password').invalid && form.get('password').touched"
        >
          <span *ngIf="form.get('password').errors['required']">Cannot be empty</span>
          <span
            *ngIf="form.get('password').errors['minlength'] &&
            form.get('password').errors['minlength']['requiredLength']"
          >
            Cannot be less {{form.get('password').errors['minlength']['requiredLength']}} symbol.
            Now: {{form.get('password').errors['minlength']['actualLength']}}
          </span>
        </span>
      </div>
      <div class="input-field">
        <input
          id="passwordConfirmation"
          type="password"
          formControlName="passwordConfirmation"
          placeholder="Confirmation password"
          [ngClass]="{
            'uncorrect': form.get('passwordConfirmation').invalid && form.get('passwordConfirmation').touched ||
            password.value !== passwordConfirmation.value && form.get('passwordConfirmation').touched,
            'correct': form.get('passwordConfirmation').valid && password.value === passwordConfirmation.value
           }"
          #passwordConfirmation
          [value]="passwordConfirmation"
        />
        <span
          class="helper-text invalid"
          *ngIf="form.get('passwordConfirmation').invalid && form.get('passwordConfirmation').touched"
        >
          <span *ngIf="form.get('passwordConfirmation').errors['required']">Cannot be empty</span>
          <span
            *ngIf="form.get('passwordConfirmation').errors['minlength'] &&
            form.get('passwordConfirmation').errors['minlength']['requiredLength']"
          >
            Cannot be less {{form.get('passwordConfirmation').errors['minlength']['requiredLength']}} symbol.
            Now: {{form.get('passwordConfirmation').errors['minlength']['actualLength']}}
          </span>
        </span>
        <br />
        <span
          class="helper-text invalid"
          *ngIf="password.value !== passwordConfirmation.value && form.get('passwordConfirmation').touched"
        >
          Passwords have to coincidence
        </span>
      </div>
      <div>
        <div class="btn">
          <button type="submit" [disabled]="form.invalid && password.value !== passwordConfirmation.value">
            Registration
          </button>
        </div>
      </div>
      <div class="auth__have">
        <span>
          Do you have an account?
        </span>
        <a routerLink="/login">Login now!</a>
      </div>
    </form>
  </div>
</section>
